### ISSUE TITLE
Create train compatibility?

### ISSUE THREAD

**Issue by DcNdrew** [tildejustin/minecart-turning#1]
I tried this with a Create train, and didn't work. Can you make a compatibility?

**Comment by tildejustin** [comment]
so the way the mod works, it only overrides the turning behavior if the riding player is not the controller of the vehicle they are in (minecart, second boat passenger, etc). from looking at create it seems they set all players as controllers of the trains they are riding. i've never used create, would it make sense to override that globally for all create trains or are there specific ones that should be like this?

**Comment by tildejustin** [comment]
after some more investigation, i have determined this is a bug in Create (they do not set vanilla's pitch and yaw fields and instead make their own with yarn names even though they're using mojmap? it's wierd). i am making an attempt to fix it but my understanding of their codebase is very poor :|

**Comment by tildejustin** [comment]
ok, i got it working, now i just need to find what of five changed classes was unnecessary :P

**Comment by tildejustin** [comment]
https://github.com/Fabricators-of-Create/Create/compare/mc1.20.1/fabric/dev...tildejustin:create:mc1.20.1/fabric/dev

**Comment by tildejustin** [comment]
done in https://github.com/Creators-of-Create/Create/pull/6089, idk when they'll merge or cherrypick to fabric though.

**Comment by tildejustin** [comment]
this feature will be implemented in create directly, through https://github.com/Creators-of-Create/Create/pull/6297
