### ISSUE TITLE
Add support for latest Minecraft version

### ISSUE THREAD

**Issue by BrailleBennett** [tildejustin/minecart-turning#4]
Mod gives an error when loading in fabric that it doesn't support this version of the game when running in fabric loader 0.16.4 on Minecraft 1.21.1. Also, does this mod turn your camera when you're driving a boat and straif?

**Comment by tildejustin** [comment]
i cannot reproduce a crash with and without fabric api on mc 1.21.1, loader 0.16.5, so if you have a crash log i'd like if you could share that...for your second question, it will apply to player passengers in boats but not the driver.
